# Решение системы линейных уравнений методом Жордана-Гаусса

In [5]:
from numpy import array,zeros

system=array([[4.,3.,-2.,4.],
             [1.,2.,1.,8.],
             [3.,2.,1.,10.]])
size=3
print(system)

def gauss(system,size):
    i=0
    while i<size:
        system[i]=system[i]/system[i][i]
        j=i+1
        while j<size:
            system[j]=system[j]-system[i]*system[j][i]
            j+=1
        i+=1
    i=size-1
    while i>=0:
        j=i-1
        while j>=0:
            system[j]=system[j]-system[i]*system[j][i]
            j-=1
        i-=1
    return system[:,size]

print(gauss(system,size))

[[ 4.  3. -2.  4.]
 [ 1.  2.  1.  8.]
 [ 3.  2.  1. 10.]]
[1. 2. 3.]
